#ifndef ALPHA_STRATEGY_H
#define ALPHA_STRATEGY_H

#include <vector>
#include "signal.h"

class AlphaStrategy {
public:
    // Default constructor
    AlphaStrategy() = default;
    // Destructor
    virtual ~AlphaStrategy() = default;
    // Returns the interval between updates in milliseconds
    virtual int interval() const = 0;
    // Returns the trading signals generated by the strategy
    virtual std::vector<Signal> getSignals() = 0;
};

#endif
